apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  selector:
    matchLabels:
      app: delivery
  replicas: 1
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: gavingunapala/ctse_micro:a2221479114c1895a24ee7d368422b6cd3236346
        ports:
        - containerPort: 3000