apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  selector:
    matchLabels:
      app: delivery
  replicas: 1
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: it19123882/ctse_it19123882:5c3404f2b7c216a5379f3d838f33a516bc0dd930
        ports:
        - containerPort: 3000