apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  selector:
    matchLabels:
      app: delivery
  replicas: 1
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: gavingunapala/ctse_micro:95f458927da71e59485c83a2b82e805e07101e1e
        ports:
        - containerPort: 3000