apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: delivery
  name: delivery
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: delivery
status:
  loadBalancer: {}